# Generated by Django 2.2.10 on 2020-05-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=120)),
                ('question', models.CharField(max_length=240)),
                ('answer', models.TextField()),
            ],
        ),
    ]
