# Generated by Django 2.2.10 on 2020-05-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('gender', models.CharField(max_length=120)),
                ('birthday', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(max_length=120, null=True)),
                ('email', models.CharField(max_length=120)),
                ('passport_id', models.CharField(max_length=120)),
                ('county', models.CharField(max_length=120)),
                ('sub_county', models.CharField(max_length=120)),
                ('ward', models.CharField(max_length=120)),
                ('farm_size', models.CharField(max_length=120)),
                ('maize', models.BooleanField(default=False)),
                ('beans', models.BooleanField(default=False)),
                ('sorghum', models.BooleanField(default=False)),
                ('daily', models.BooleanField(default=False)),
                ('chicken', models.BooleanField(default=False)),
                ('fish', models.BooleanField(default=False)),
                ('bee', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('red_meat', models.BooleanField(default=False)),
            ],
        ),
    ]
