# Generated by Django 2.2.10 on 2020-05-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('county', models.CharField(max_length=120)),
                ('sub_county', models.CharField(max_length=120)),
                ('ward', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('comments', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
